AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.8
    Architectures:
      - x86_64

Resources:
  AutomationsTurnOffEc2:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: ec2-turnoff-automation
        CodeUri: src/ec2-turnoff/
        Policies:
          - Statement:
              - Sid: EC2Policy
                Effect: Allow
                Action:
                  - ec2:StopInstances
                Resource: "*"
        Events:
          ScheduleWeek:
            Type: Schedule
            Properties:
              Enabled: false
              Schedule: "cron(0 2 ? * MON-SAT *)"
          ScheduleWeekend:
            Type: Schedule
            Properties:
              Enabled: true
              Schedule: "cron(0 23 ? * SAT-SUN *)"

  AutomationsTurnOnEc2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ec2-turnonautomation
      CodeUri: src/ec2-turnon/
      Policies:
        - Statement:
            - Sid: EC2Policy
              Effect: Allow
              Action:
                 - ec2:StartInstances
              Resource: "*"
      Events:
        ScheduleWeek:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: "cron(0 9 ? * MON-FRI *)"
        ScheduleWeekend:
            Type: Schedule
            Properties:
              Enabled: true
              Schedule: "cron(0 11 ? * SAT-SUN *)"