AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Description: "O nome do bucket S3"
    Type: String
    Default: "infra-bucket-${AWS::AccountId}"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      BucketName: !Ref BucketName
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      MetricsConfigurations:
        - Id: !Sub "${BucketName}"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: DenyNonSSLRequests
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
          Condition:
            Bool:
              aws:SecureTransport: 'false'