AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::SecretsManager-2020-07-23

Parameters:
  VpcId: 
    Type: String
    Description: ID da VPC
    Default: "vpc-xxxxxxxx"

  Subnet1:
    Type: String
    Description: ID da Subnet 1
    Default: "subnet-xxxxxxxx"

  Subnet2:
    Type: String
    Description: ID da Subnet 2
    Default: "subnet-xxxxxxxx"

  Subnet3:
    Type: String
    Description: ID da Subnet 3
    Default: "subnet-xxxxxxxx"

Resources:
  LambdaRotationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para lambda de rotação de secrets do RDS
      GroupName: 'lambda-secret-rotation-sg'
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 443
          ToPort: 443
          IpProtocol: tcp
        - CidrIp: "10.0.0.0/8"
          FromPort: 0
          ToPort: 65535
          IpProtocol: tcp
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/8"
          FromPort: 0
          ToPort: 65535
          IpProtocol: tcp
      VpcId: !Ref VpcId

  SecretRotationScheduleSU:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      RotateImmediatelyOnUpdate: false
      SecretId: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rds/user/ddladmin-SzyQHe'
      HostedRotationLambda:
        RotationType: PostgreSQLSingleUser
        RotationLambdaName: secrets-manager-rotation-single-user
        VpcSecurityGroupIds: !GetAtt LambdaRotationSecurityGroup.GroupId
        VpcSubnetIds: !Join [",", [!Ref Subnet1, !Ref Subnet2, !Ref Subnet3]]
      RotationRules:
        Duration: 2h
        ScheduleExpression: 'rate(7 days)'

  SecretRotationScheduleMU:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      RotateImmediatelyOnUpdate: false
      SecretId: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rds/user/user_rds_rca_viewer-NJ1r3C'
      HostedRotationLambda:
        SuperuserSecretArn: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rds/user/ddladmin-SzyQHe'
        RotationType: PostgreSQLMultiUser
        RotationLambdaName: secrets-manager-rotation-multi-user
        VpcSecurityGroupIds: !GetAtt LambdaRotationSecurityGroup.GroupId
        VpcSubnetIds: !Join [",", [!Ref Subnet1, !Ref Subnet2, !Ref Subnet3]]
      RotationRules:
        Duration: 2h
        ScheduleExpression: 'rate(7 days)'