AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SecretNameViewer:
    Description: "Nome do segredo para o usu치rio de leitura"
    Type: String
    Default: "rds/user/rds_exemplo_viewer"

  SecretNameWriter:
    Description: "Nome do segredo para o usu치rio de escrita"
    Type: String
    Default: "rds/user/rds_exemplo_writer"

Resources:
  SecretViewer:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Ref SecretNameViewer
      Description: "Usu치rio de leitura para o Aurora"
      SecretString: '{"host":"rds-read-only.endpoint.proxy.sa-east-1.rds.amazonaws.com","port":"5432","username":"rds_exemplo_viewer","password":"senha_leitura","database":"exemploDB"}'
      Tags:
        - Key: Name
          Value: !Ref SecretNameViewer

  SecretWriter:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Ref SecretNameWriter
      Description: "Usu치rio de escrita para o Aurora"
      SecretString: '{"host":"aurora-proxy.proxy.sa-east-1.rds.amazonaws.com","port":"5432","username":"rds_exemplo_writer","password":"senha_escrita","database":"exemploDB"}'
      Tags:
        - Key: Name
          Value: !Ref SecretNameWriter